name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy with Oryx (Node 22)
        uses: Azure/static-web-apps-deploy@v1
        env:
          ORYX_NODE_VERSION: '22.12.0'   # force oryx to use node v22
          ENABLE_DYNAMIC_INSTALL: 'true'  # if oryx do not have such version then install it dynamically
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_DUNE_0D0C6C510 }}
          action: upload
          app_location: "/"               
          api_location: ""                
          output_location: "dist"        

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_DUNE_0D0C6C510 }}
          action: close
